# ___NumPy Practice Session___
![image](img.png)

In [2]:
# import this library in j.notebook/VScode
import numpy as np

## _Creating an array using numpy_ 
_Array mean kataar, remember example of school assembly, 1D array 1 katar, 2D array 2 kataar._

In [3]:
np.array(["pakora", "samosa", "raita"])

array(['pakora', 'samosa', 'raita'], dtype='<U6')

In [4]:
food = np.array(["pakora", "samosa", "raita"])
food

array(['pakora', 'samosa', 'raita'], dtype='<U6')

In [5]:
price= np.array([5,5,5])
price
#1-D array

array([5, 5, 5])

In [6]:
type(price) #ndarray nd means n-dimensional array 

numpy.ndarray

In [7]:
type(food)

numpy.ndarray

In [8]:
len(food)

3

In [9]:
len(price)

3

In [10]:
price[2]

5

In [11]:
price[0:] #[0:] its mean zero to end all values

array([5, 5, 5])

In [12]:
# if >>> food["Samosa"] it have an error, so write this command
food[1]

'samosa'

In [13]:
# Mean of this array
price.mean()

5.0

In [14]:
# range method, start from zeros , to build and array
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [15]:
# range method, start from ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [16]:
# empty
np.empty(5) 
# assignment why here is 1's why not 0's

array([1., 1., 1., 1., 1.])

In [17]:
# arange means a range from 0 to 10 (10 is exclusive because it starts from zero)
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
# specify range start from some specific range like 2 to 20
np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [19]:
#specific range with interval. 2 starting point, 20 upto range and 2 is interval. numpy follow this sequence.
np.arange(2,20, 2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [21]:
# table of five , 5 ka pahara
np.arange(0,55,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [22]:
# table of five , 6 ka pahara
np.arange(0,66,6)

array([ 0,  6, 12, 18, 24, 30, 36, 42, 48, 54, 60])

In [23]:
# linspace, yani specific interval p 10 number ajy
np.linspace(0, 100, num=10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [24]:
# linspace yani specific interval p 5 number ajy
np.linspace(1, 10, num=5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [25]:
#specify your data type 
np.ones(50, dtype=np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1], dtype=int64)

In [26]:
np.ones(50, dtype=np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# ___Array Functions___

## ___1-D array___

In [27]:
a=np.array([10,20,30,50,2,5.2,10.5,3.2,320])
a
# a is = to np.array > after a. "there will be lots of functions we can use these numpy functions". can see manual of numpy.

array([ 10. ,  20. ,  30. ,  50. ,   2. ,   5.2,  10.5,   3.2, 320. ])

In [28]:
# sorting this array
a.sort()
a

array([  2. ,   3.2,   5.2,  10. ,  10.5,  20. ,  30. ,  50. , 320. ])

In [29]:
a.cumsum()
a

array([  2. ,   3.2,   5.2,  10. ,  10.5,  20. ,  30. ,  50. , 320. ])

In [30]:
b=np.array([10.2,11.5,22,5,50.5])
b

array([10.2, 11.5, 22. ,  5. , 50.5])

In [31]:
# concatinate means addition of array
np.concatenate((a,b))

array([  2. ,   3.2,   5.2,  10. ,  10.5,  20. ,  30. ,  50. , 320. ,
        10.2,  11.5,  22. ,   5. ,  50.5])

In [32]:
# another exapmple of concatinate
c= np.concatenate((a,b))
c

array([  2. ,   3.2,   5.2,  10. ,  10.5,  20. ,  30. ,  50. , 320. ,
        10.2,  11.5,  22. ,   5. ,  50.5])

In [34]:
# sorting of this c array
np.sort(c)


array([  2. ,   3.2,   5. ,   5.2,  10. ,  10.2,  10.5,  11.5,  20. ,
        22. ,  30. ,  50. ,  50.5, 320. ])

In [35]:
c.sort()
c

array([  2. ,   3.2,   5. ,   5.2,  10. ,  10.2,  10.5,  11.5,  20. ,
        22. ,  30. ,  50. ,  50.5, 320. ])

## ___2-D array___

In [36]:
a= np.array([[1,2,3], [5,6,7]])
a

array([[1, 2, 3],
       [5, 6, 7]])

In [37]:
b= np.array([[4,5,6],[7,8,9]])
b

array([[4, 5, 6],
       [7, 8, 9]])

In [43]:
c= np.concatenate((a,b))
c

array([[1, 2, 3],
       [5, 6, 7],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
# axis must follow understand it. in mumpy axis0 is y axix, axis1 is x axis.
d= np.concatenate((a,b), axis=0)
d

array([[1, 2, 3],
       [5, 6, 7],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
e= np.concatenate((a,b), axis=1)
e

array([[1, 2, 3, 4, 5, 6],
       [5, 6, 7, 7, 8, 9]])

In [51]:
c.ndim

2

In [49]:
d.ndim

2

In [50]:
e.ndim #  .ndim = n dimensionn? how many dimensions? Ans: 2D.

2

In [ ]:
a.size   # calculte number of size of elements

6

In [52]:
e.size

12

In [ ]:
a.shape   # shape : i,j,k i mean matrix , rows, coloumns

(2, 3)

In [53]:
e.shape

(2, 6)

In [54]:
a= np.arange(9) #3*3
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [55]:
# reshape, 2D
b=a.reshape(3,3) #3*3
b


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [56]:
# reshape
np.reshape(a, newshape=(1,9), order="c") #3*3



array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [57]:
# covert 1D into 2D
a=np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
a.shape

(9,)

In [59]:
# row wise 2D coversion
b= a[np.newaxis, :]
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [60]:
b.shape

(1, 9)

In [61]:
# coloumn wise 2D conversion
c= a[:, np.newaxis]
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [62]:
c.shape

(9, 1)

In [63]:
# multiplication *, addition+, sum a.sum(), a.mean()  
a*6

array([ 6, 12, 18, 24, 30, 36, 42, 48, 54])

In [64]:
a.sum()

45

In [65]:
a.mean()

5.0

# ___Practical Examples of 1D 2D 3D Array.___

## _1-D Array_

In [66]:
import numpy as np
a= np.array([5,5,5])
a

array([5, 5, 5])

In [67]:
type(a)

numpy.ndarray

In [68]:
len(a)

3

In [69]:
import numpy as np
a= np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [70]:
# how to creat an array

import numpy as np
a= np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [71]:
type(a)

numpy.ndarray

In [72]:
len(a)

5

In [73]:
b= np.zeros(2)
b

array([0., 0.])

In [74]:
c=np.ones(3)
c

array([1., 1., 1.])

In [75]:
# creat an empty array with 2 elements
d= np.empty(3)
d

array([1., 1., 1.])

In [76]:
# with specific range of elements
b=np.arange(2,20)
b

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [77]:
# with range of elements
a=np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [78]:
# continue...
c=np.arange(2, 22, 2)
c

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [79]:
#linerly spaced array
d=np.linspace(0,10,num=5) #gives us 5 nums
d

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

## _2-D Array_

In [80]:
import numpy as np
a= np.array([[5,5,5],[5,5,5],[5,5,5]])
a

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [81]:
import numpy as np
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [82]:
import numpy as np
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [83]:
np.empty((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [84]:
type(a)

numpy.ndarray

In [85]:
len(a)

3

In [86]:
a[0]

array([5, 5, 5])

In [87]:
a[0:]

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [88]:
import numpy as np
a= np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [89]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [90]:
np.empty((3,5))

array([[4.67296746e-307, 1.69121096e-306, 1.33512376e-306,
        6.23054633e-307, 2.22522597e-306],
       [1.33511969e-306, 1.37962320e-306, 9.34604358e-307,
        9.79101082e-307, 1.78020576e-306],
       [1.69119873e-306, 2.22522868e-306, 1.24611809e-306,
        8.06632139e-308, 1.60221208e-306]])

## _3-D Array_

In [95]:
#making and reshaping a 3D array
c=np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

Numpy userguide
https://numpy.org/doc/stable/user/index.html#user